name: Build and Deploy Bllok Site

on:
  push:
    branches: [main]  
  workflow_dispatch:
  workflow_run:
    workflows: ["Daily Gemini Blog Post"]
    types:
      - completed

      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trust GitHub workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Generate static site
        uses: eltonkola/bllok-action@v1
        with:
          template: tema
          input: blog
          output: public
          rootpath: bllok_skenderbeu

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
